---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - "tmp/**/*"
  - "log/**/*"
  - "node_modules/**/*"
  - "coverage/**/*"
  - ".git/**/*"
  - "storage/**/*"
  - "public/**/*"
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
domains: []
reporters:
  - require_not_found
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000